### ISSUE TITLE
`RemoveStringFlag` should remove method calls & conditions when comparing equal Strings

### ISSUE THREAD

**Issue by bsgongang** [openrewrite/rewrite-feature-flags#40]
## I was using the OpenRewrite rewrite-feature-flags, RemoveStringFlag recipe to remove a feature flag in code.
The recipe replaced the feature flag call with the expected value, but could not use the replaced value to simplify the code.

Here is my code:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: com.openrewrite.featureflags.RemoveFlag
displayName: Remove feature flags
recipeList:
 -org.openrewrite.featureflags.RemoveStringFlag:
      methodPattern: com.my.org.impl.Client getFlagAssignment(String, String, String)
      featureKey: “feature_266154"
      replacementValue: "T1” 
```
### code to refactor with above recipe:
```java
private com.my.org.impl.Client client; 

String treatment = client.getFlagAssignment(“feature_266154”, session, clientId); 

if (T1.equals(treatment)) { 
doTreatment(); 
} else { 
doNonTreatment(); 
}
```
After running the recipe the output 

### code transformation output
```java
private com.my.org.impl.Client client; 

String treatment = T1; 

if (T1.equals(treatment)) { 
doTreatment(); 
} else { 
doNonTreatment(); 
}
```
### Expectation
```
doTreatment();
```

issue: `if (T1.equals(treatment))`  is not being simplified with the treatment value which is `T1`; I was expecting further simplification, i`f (T1.equants(treament == T1)) => if (true)`

## Describe the solution you'd like
We should enhance the remove feature flag recipe to evaluate expressions with the targeted value, simplify the code, and generate a diff that developers wont have any change to do

## Have you considered any alternatives or workarounds?
Trying to add some static analysis recipes or use ast-grep rules to evaluate all expressions with the feature flag assigned value

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)? Yes, I am interested

Sure, I would like to work on this. I need a POC from openrewrite with whom i can collaborate to get it done
